export { default as dailySchedulePlanner } from "./daily-schedule-planner.png";
export { default as theBigQuiz } from "./the-big-quiz.png";
export { default as natParkTravelGuide } from "./nat-park-travel-guide.png";
export { default as randomPasswordGenerator } from "./password-generator.png";
export { default as weatherForecast } from "./weather-forecast-finder.png";
export { default as bostonStreetCuisine } from "./boston-street-cuisine.png";
export { default as taskSandwich } from "./task-sandwich.png";
export { default as bostonStreetCuisineMobile } from "./boston-street-cuisine-mobile.jpg";
export { default as taskSandwichMobile } from "./task-sandwich-mobile.jpg";