export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header/index2";
export { default as Main } from "./Main";
export { default as Map } from "./Map";
export { default as Navbar } from "./Navbar/index2";
export { default as Projects } from "./Projects/index2";
export { default as Techs } from "./Techs";